
package com.upsoft.login.support.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlatformWebServiceImplService", targetNamespace = "http://webservice.systemweb.upsoft.com/", wsdlLocation = "http://127.0.0.1:8080/up_systemweb/webservice/platformWS?wsdl")
public class PlatformWebServiceImplService
    extends Service
{

    private final static URL PLATFORMWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLATFORMWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PLATFORMWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.systemweb.upsoft.com/", "PlatformWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/up_systemweb/webservice/platformWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLATFORMWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PLATFORMWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PlatformWebServiceImplService() {
        super(__getWsdlLocation(), PLATFORMWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PlatformWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLATFORMWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PlatformWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PLATFORMWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PlatformWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLATFORMWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PlatformWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlatformWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlatformWebService
     */
    @WebEndpoint(name = "PlatformWebServiceImplPort")
    public PlatformWebService getPlatformWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.systemweb.upsoft.com/", "PlatformWebServiceImplPort"), PlatformWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlatformWebService
     */
    @WebEndpoint(name = "PlatformWebServiceImplPort")
    public PlatformWebService getPlatformWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.systemweb.upsoft.com/", "PlatformWebServiceImplPort"), PlatformWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLATFORMWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PLATFORMWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PLATFORMWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
