
package com.upsoft.login.support.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlatformWebService", targetNamespace = "http://webservice.systemweb.upsoft.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PlatformWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getPermissionOrgIds(
        @WebParam(name = "userId", partName = "userId")
        String arg0);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getUserInfoByToken(
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * 
     * @param systemCode
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String queryMenusBySysCodeAndUserId(
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "systemCode", partName = "systemCode")
        String systemCode);

    /**
     * 
     * @param sysCode
     * @param permissionNo
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getBtnPermission(
        @WebParam(name = "permissionNo", partName = "permissionNo")
        String permissionNo,
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "sysCode", partName = "sysCode")
        String sysCode);

    /**
     * 
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean logout(
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * 
     * @param menuId
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String queryMenusByMenuIdAndUserId(
        @WebParam(name = "menuId", partName = "menuId")
        String menuId,
        @WebParam(name = "userId", partName = "userId")
        String userId);

    /**
     * 
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean checkLogin(
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * 
     * @param orgCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getChildOrgCodes(
        @WebParam(name = "orgCode", partName = "orgCode")
        String orgCode);

    /**
     * 
     * @param orgId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String iterateOrgById(
        @WebParam(name = "orgId", partName = "orgId")
        String orgId);

    /**
     * 
     * @param userId
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getSystemCodeByUserIdInRole(
        @WebParam(name = "userId", partName = "userId")
        String userId);

    /**
     * 
     * @param password
     * @param loginId
     * @param systemCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String login(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "systemCode", partName = "systemCode")
        String systemCode);

    /**
     * 
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getDefinedSystemCodeAndName();

    /**
     * 
     * @param systemCode
     * @param parentCode
     * @param userId
     * @param parentId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getOrgTreeInPermission(
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "parentId", partName = "parentId")
        String parentId,
        @WebParam(name = "parentCode", partName = "parentCode")
        String parentCode);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getLoginInfoByToken(
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getUser(
        @WebParam(name = "userId", partName = "userId")
        String userId);

    /**
     * 
     * @param systemCode
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String queryAccordionMenusByCondition(
            @WebParam(name = "userId", partName = "userId")
            String userId,
        @WebParam(name = "systemCode", partName = "systemCode")
        String systemCode);

    /**
     * 
     * @param orgId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getOrg(
        @WebParam(name = "orgId", partName = "orgId")
        String orgId);

    /**
     * 
     * @param systemCode
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getUserSelectInPermission(
        @WebParam(name = "userId", partName = "userId")
        String userId);
   
    @WebMethod
    @WebResult(partName = "return")
    public String getUserOrgTreeInPermission(
            @WebParam(name = "userId", partName = "userId")
            String userId,
            @WebParam(name = "orgId", partName = "orgId")
            String orgId);
    
    @WebMethod
    @WebResult(partName = "return")
    public String getUserOrgTreeByOrgId(@WebParam(name = "orgId", partName = "orgId")
    String orgId,@WebParam(name = "userId", partName = "userId")
    String userId);
    
    @WebMethod
    @WebResult(partName = "return")
	public String querySysCodeAndNameByUserId( @WebParam(name = "userId", partName = "userId")String userId);

    @WebMethod
    @WebResult(partName = "return")
    public String getDictSelect(@WebParam(name = "parentNodeId", partName = "parentNodeId")String parentNodeId);

    @WebMethod
    @WebResult(partName = "return")
	public String getDictValue1(@WebParam(name = "parentNodeId", partName = "parentNodeId")String parentNodeId,
						@WebParam(name = "code", partName = "code")String code);

    @WebMethod
    @WebResult(partName = "return")
	public String getListDataBySql(@WebParam(name = "sql", partName = "sql")String sql, 
			@WebParam(name = "paramsStr", partName = "paramsStr")String paramsStr);
   
    @WebMethod
    @WebResult(partName = "return")
    public void saveLoginLog(@WebParam(name = "loginLog", partName = "loginLog")String loginLog);
    
    /**
	 * 保存操作日志
	 * @date 2017年9月2日 下午3:29:25
	 * @author 胡毅
	 */
    @WebMethod
    @WebResult(partName = "return")
	public void saveLog(@WebParam(name = "loginLog", partName = "loginLog")String loginUserStr,
			@WebParam(name = "uri", partName = "uri")String uri,
			@WebParam(name = "className", partName = "className")String className,
			@WebParam(name = "methodName", partName = "methodName")String methodName,
			@WebParam(name = "contentStr", partName = "contentStr")String contentStr);
    /**
     * 验证旧密码
     * @date 2017年9月17日 下午4:24:33
     * @author 胡毅
     * @param loginId
     * @param oldPwd
     * @param inputPwd
     * @return
     */
    @WebMethod
    @WebResult(partName = "return")
    public Boolean validUserPwd(@WebParam(name = "loginId", partName = "loginId")String loginId,
					    		@WebParam(name = "oldPwd", partName = "oldPwd")String oldPwd, 
					    		@WebParam(name = "inputPwd", partName = "inputPwd")String inputPwd);
    @WebMethod
    @WebResult(partName = "return")
    public void saveUser(@WebParam(name = "userStr", partName = "userStr")String userStr);
}
